### ISSUE TITLE
Quirrel queue is blocked indefinitely by using `exclusive: true`

### ISSUE THREAD

**Issue by mattjis** [quirrel-dev/quirrel#739] opened 2021-08-19 08:05 UTC
I'm not too sure what the issue is, but my api endpoints aren't being called. 

Are you able to lookup my account and figure out why it's not working?

The domain is hal.vercel.app

**Comment by mattjis** [comment] 2021-08-19 08:06
When I schedule them everything seems fine:

	{
		id: '6885672091808',
		endpoint: 'https://hal.vercel.app/api/products/raffle',
		body: null,
		runAt: 2021-08-19T07:00:34.449Z,
		exclusive: true,
		retry: [],
		count: 1,
		delete: [Function: delete],
		invoke: [Function: invoke]
	}

But the endpoint is never called :(

**Comment by Skn0tt** [comment] 2021-08-19 08:15
Hi @mattjis! When did you enqueue this job? I suspect it could be related to [a change](https://github.com/quirrel-dev/owl/pull/176) in Owl (Quirrel's scheduler) that I [merged](https://github.com/quirrel-dev/quirrel/pull/735) 2 days ago.

**Comment by mattjis** [comment] 2021-08-19 08:26
Hey Simon!

I've attempted to queue about 5 or 10 jobs over the past couple of hours and none of them are triggering.

**Comment by Skn0tt** [comment] 2021-08-19 08:27
Thank you. Looking into it now.

**Comment by mattjis** [comment] 2021-08-19 08:28
I did get a weird error before it stopped working, probably unrelated to Quirrel but I'll paste it here anyway.

	[POST] /api/products/raffle
	13:30:46:07
	2021-08-19T05:30:46.782Z	ca5c8e12-1a82-4ed9-bb23-360ddbc5acf4	ERROR	TypeError: Cannot read property 'length' of undefined
		at getLens (/var/task/node_modules/base64-js/index.js:23:17)
		at Object.toByteArray (/var/task/node_modules/base64-js/index.js:55:14)
		at unpackMessage (/var/task/node_modules/secure-e2ee/dist/base-encryptor.js:104:51)
		at Encryptor.<anonymous> (/var/task/node_modules/secure-e2ee/dist/base-encryptor.js:156:30)
		at step (/var/task/node_modules/secure-e2ee/dist/base-encryptor.js:75:23)
		at Object.next (/var/task/node_modules/secure-e2ee/dist/base-encryptor.js:56:53)
		at /var/task/node_modules/secure-e2ee/dist/base-encryptor.js:50:71
		at new Promise (<anonymous>)
		at __awaiter (/var/task/node_modules/secure-e2ee/dist/base-encryptor.js:46:12)
		at Encryptor.BaseEncryptor.decrypt (/var/task/node_modules/secure-e2ee/dist/base-encryptor.js:151:16)
	2021-08-19T05:30:46.782Z	ca5c8e12-1a82-4ed9-bb23-360ddbc5acf4	ERROR	TypeError: Cannot read property 'length' of undefined
		at getLens (/var/task/node_modules/base64-js/index.js:23:17)
		at Object.toByteArray (/var/task/node_modules/base64-js/index.js:55:14)
		at unpackMessage (/var/task/node_modules/secure-e2ee/dist/base-encryptor.js:104:51)
		at Encryptor.<anonymous> (/var/task/node_modules/secure-e2ee/dist/base-encryptor.js:156:30)
		at step (/var/task/node_modules/secure-e2ee/dist/base-encryptor.js:75:23)
		at Object.next (/var/task/node_modules/secure-e2ee/dist/base-encryptor.js:56:53)
		at /var/task/node_modules/secure-e2ee/dist/base-encryptor.js:50:71
		at new Promise (<anonymous>)
		at __awaiter (/var/task/node_modules/secure-e2ee/dist/base-encryptor.js:46:12)
		at Encryptor.BaseEncryptor.decrypt (/var/task/node_modules/secure-e2ee/dist/base-encryptor.js:151:16)
	RequestId: ca5c8e12-1a82-4ed9-bb23-360ddbc5acf4 Error: Runtime exited with error: exit status 1
	Runtime.ExitError

**Comment by Skn0tt** [comment] 2021-08-19 08:29
Oh, that is indeed not unrelated! Could you update to v1.7.1 and tell me if that fixes your issue?

**Comment by mattjis** [comment] 2021-08-19 08:31
@Skn0tt I'm already on 1.7.1

`"quirrel": "^1.7.1",`

**Comment by Skn0tt** [comment] 2021-08-19 08:32
Hmm, interesting. The log you posted is related to Quirrel's E2E encryption and was fixed via https://github.com/quirrel-dev/quirrel/pull/677. I then suspect you're observing a different error now. Looking into it.

**Comment by mattjis** [comment] 2021-08-19 08:34
Should I try deleting `node_modules` and `package-lock.json` to reinstall everything?

**Comment by mattjis** [comment] 2021-08-19 08:36
This is what my enqueue code looks like too, in case there's anything helpful:

	await RaffleQueue.enqueue(null, {
		id: "6771665862836",
		override: true,
		exclusive: true,
		runAt: new Date("2021-09-01T06:00:00.000Z")
	})

**Comment by Skn0tt** [comment] 2021-08-19 08:39
No, that won't help. I had a look at Quirrel's production database, and it seems like there's a case where queues with `exclusive: true` can get blocked indefinitely. If you need a quick fix for this, I recommend to change the name of the queue (place it at a different API endpoint) and don't use the `exclusive: true` feature for now.
I'll need to do some more digging to find the root cause of this issue. Is it urgent for you? If yes, I can try looking into it tonight.

**Comment by mattjis** [comment] 2021-08-19 08:40
Oh something to note as well. 

The `enqueue` which lead to that error I pasted above was `enqueued` with version 1.7.0, and updated to 1.7.1 before it called back. Not sure if that would affect things.

**Comment by mattjis** [comment] 2021-08-19 08:43
Whenever you get a chance! We'll just have to delay a few products from releasing until Monday, which isn't a huge issue.

**Comment by Skn0tt** [comment] 2021-08-19 08:44
Okay. Will try sorting this tonight, but can't guarantee anything.

**Comment by Skn0tt** [comment] 2021-08-19 14:55
Digging through the logs, I find some entries that make me think your Queue enqueues jobs into itself. Can you confirm that?

**Comment by Skn0tt** [comment] 2021-08-19 16:11
I did some more testing, and this seems to indeed be the case. Here's roughly what happens:

1. You enqueue job A (exclusive, override: true).
2. Job A starts execution.
3. Your application is called, which will enqueue a new job under the same ID (let's call it job A').
3. Job A finishes execution, and consequently deletes all of its data, because it assumes that data is no longer needed.
4. Job A' starts execution, but all it's data has been deleted in the previous step! Undefined behaviour happens, and leads to your queue being blocked indefinitely.

This can not only occur because a queue enqueues into itself, but also because of bad timing in general. I'll prioritise introducing a fix for that.
For your specific case, I think there's an easier way to go forward:

1. reset your queue by moving it to another endpoint. `/api/products/raffle` is in an undefined state at the moment, and I'd prefer to *not* fix that manually in the database. So maybe rename it to `/api/products/raffle?reset=1` or `/api/products/raffle-2`.
2. make sure that, while executing a job, you don't enqueue a job with the same ID.

Please let me know if this helps you.

**Comment by mattjis** [comment] 2021-08-19 16:26
Yes that's right.

First I enqueue the job when people enter a raffle:

	await RaffleQueue.enqueue(null, {
		id: String(sanityProduct.shopifyId),
		override: true,
		exclusive: true,
		runAt: new Date(sanityProduct.date)
	})

And then when the raffle has ended it needs to be run x (unknown) amount of times to charge all of the winners. Each batch sets up another callback via quirrel using:

	return RaffleQueue.enqueue(
		{ variants: product.variants },
		{
			id: String(product.id),
			exclusive: true,
			override: true,
			delay: 1
		}
	)

**Comment by mattjis** [comment] 2021-08-19 16:28
The thing is though, to me, the queue ID being the product ID is a good way of making sure it's never called back multiple times. And I use it to look up all the product information required to finalise the raffle.

**Comment by Skn0tt** [comment] 2021-08-19 16:30
I see. Is there a way for you to split up the two kinds of work into two different queues?

**Comment by Skn0tt** [comment] 2021-08-19 16:31
Or by appending some incrementing counter to the second call's ID?

**Comment by mattjis** [comment] 2021-08-19 16:35
Well there's really only one job. 

If I sent `null` as the payload in "part 2" it would work exactly the same. It's just a double check in case quantities don't match.

**Comment by mattjis** [comment] 2021-08-19 16:37
I guess a counter could work, but it does concern me that I'll somehow end up queuing multiple for the same product and then charge extra people accidentally.

**Comment by mattjis** [comment] 2021-08-19 16:41
It only sets up another queue once it's finished processing — as Vercel has a 60s limit on serverless functions. 

So that's why I have it set up to "start again" under the same ID to continue where it left off.

**Comment by Skn0tt** [comment] 2021-08-19 16:41
It seems like I was able to fix the issue: https://github.com/quirrel-dev/owl/pull/180

I hope I can get this merged & shipped tomorrow 🤞

**Comment by mattjis** [comment] 2021-08-19 16:43
Thank you!

**Comment by mattjis** [comment] 2021-08-19 16:49
> /api/products/raffle is in an undefined state at the moment

Will I have to change endpoints or ids?

**Closed** 2021-08-20 13:07 UTC

**Comment by Skn0tt** [comment] 2021-08-20 13:17
Alright, fix is merged & deployed! You'll have to change the endpoint.
